baseURL = 'https://kouizine.netlify.app'
languageCode = 'en-us'
title = 'Kouizine'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
